sudo: required
services: 
    - docker

before_install:
    - docker build -t hansherrlich/react-test -f ./client/Dockerfile.dev ./client

srcipt: 
    - docker run -e CI=true hansherrlich/react-test npm test -- --coverage

after_success: 
    - docker build -t hansherrlich/multi-client -f ./client   
    - docker build -t hansherrlich/multi-nginx -f ./nginx
    - docker build -t hansherrlich/multi-server -f ./server
    - docker build -t hansherrlich/multi-worker -f ./worker
    
    # log into docker 
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
    - docker push hansherrlich/multi-client
    # push all images to docker 
    - docker push hansherrlich/multi-client
    - docker push hansherrlich/multi-nginx 
    - docker push hansherrlich/multi-server
    - docker push hansherrlich/multi-worker